//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalCaseStudy.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class BatchDetail
    {
        [Required(ErrorMessage ="Please enter Batch No")]
        [Range(1,9999,ErrorMessage ="Please enter positive value")]
        public int batchno { get; set; }
        [Required(ErrorMessage ="Please choose Course")]
        public string course { get; set; }
        [Required(ErrorMessage ="Please select timing")]
        public string timing { get; set; }
        [Required(ErrorMessage = "Please enter Students")]
        [Range(1, 9999, ErrorMessage = "Please enter positive value")]
        public Nullable<int> noofstd { get; set; }
        [Required(ErrorMessage = "Please enter Vacancies")]
        [Range(1, 9999, ErrorMessage = "Please enter positive value")]
        public Nullable<int> vacant { get; set; }
    }
}
