//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalCaseStudy.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class EnrollDetail
    {
        [Required(ErrorMessage ="Please enter City")]
        public string city { get; set; }
        [Required(ErrorMessage ="Please enter PIN")]
        [Range(1,999999,ErrorMessage ="Enter Valid PIN")]
        public int pin { get; set; }
        [Required(ErrorMessage ="Please enter No of Centers")]
        [Range(1,99,ErrorMessage ="Please enter positive value")]
        public Nullable<int> noofcenters { get; set; }
        [Required(ErrorMessage = "Please enter Enrollments")]
        [Range(1, 9999, ErrorMessage = "Please enter positive value")]
        public Nullable<int> totalenroll { get; set; }
    }
}
