//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalCaseStudy.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class StudentDetail
    {
        [Required(ErrorMessage ="Please enter name")]
        public string Studentname { get; set; }
        [Required(ErrorMessage = "Please enter Roll No")]
        [Range(1,9999,ErrorMessage ="Please enter positive number")]
        public int rollno { get; set; }
        [Required(ErrorMessage ="Please choose gender")]
        public string gender { get; set; }
        [Required(ErrorMessage ="Please enter age")]
        [Range(1, 150, ErrorMessage = "Please enter positive number")]
        public Nullable<int> age { get; set; }
        [Required(ErrorMessage = "Please select Course")]
        public string course { get; set; }
        [Required(ErrorMessage = "Please enter address")]
        public string address { get; set; }
    }
   
}
